kind: pipeline
name: project-manager

steps:
- name: user-client
  image: node:16-alpine
  commands:
  - cd user-client
  - yarn run test --watchAll=false

- name: user-api
  image: node:16-alpine
  commands:
  - cd user-api
  - yarn install
  - yarn run lint
  - yarn run test
