kind: pipeline
name: nest-api

steps:
- name: install
  image: node:16-alpine
  commands:
  - cd nest-api
  - yarn install

- name: lint
  image: node:16-alpine
  commands:
  - yarn run lint

- name: test
  image: node:16-alpine
  commands:
  - yarn run test
