kind: pipeline
type: docker
name: user-client

steps:
- name: build
  image: node:16-alpine
  commands:
    - cd user-client
    - yarn install
  volumes:
    - name: user-client-cache
      path: /drone/src/user-client/node_modules

- name: lint
  image: node:16-alpine
  commands:
    - cd user-client
    - yarn run lint

- name: test
  image: node:16-alpine
  commands:
    - cd user-client
    - yarn run test --watchAll=false

---
kind: pipeline
type: docker
name: api

steps:
- name: build
  image: node:16-alpine
  commands:
    - cd api
    - yarn install
  volumes:
    - name: api-cache
      path: /drone/src/api/node_modules

- name: lint
  image: node:16-alpine
  commands:
    - cd api
    - yarn run lint

- name: test
  image: node:16-alpine
  commands:
    - cd api
    - yarn run test
