kind: pipeline
type: docker
name: user-client

steps:
- name: dependency install
  image: node:16-alpine
  commands:
    - cd user-client
    - yarn install
  volumes:
    - name: user-client-cache
      path: /drone/src/user-client/node_modules

- name: lint
  image: node:16-alpine
  commands:
    - cd user-client
    - yarn run lint
    - yarn run test --watchAll=false

- name: test
  image: node:16-alpine
  commands:
    - cd user-client
    - yarn run test --watchAll=false

---
kind: pipeline
type: docker
name: user-api

steps:
- name: dependency install
  image: node:16-alpine
  commands:
    - cd user-api
    - yarn install
  volumes:
    - name: user-api-cache
      path: /drone/src/user-api/node_modules

- name: lint
  image: node:16-alpine
  commands:
    - cd user-api
    - yarn run lint

- name: test
  image: node:16-alpine
  commands:
    - cd user-api
    - yarn run test
