kind: pipeline
name: user-api

steps:
- name: install
  image: node:16-alpine
  commands:
  - cd user-api
  - yarn install

- name: lint
  image: node:16-alpine
  commands:
  - cd user-api
  - yarn run lint

- name: test
  image: node:16-alpine
  commands:
  - cd user-api
  - yarn run test
